// GENERATED by scripts/build-images.mjs — do not edit by hand.
// Filenames are content-hashed, so /img/items/* can be served immutable.

export interface ItemImage {
  /** 160px tile shown in listings. */
  thumb: string;
  /** Up to 1200px, fetched only when the lightbox opens. */
  full: string;
  w: number;
  h: number;
}

export const ITEM_IMAGES: Record<string, ItemImage> = {
  "agotnes-mattress": { thumb: "/img/items/agotnes-mattress.6f04674c.webp", full: "/img/items/agotnes-mattress.3dc87dd5.full.webp", w: 1200, h: 1200 },
  "andlig-knives": { thumb: "/img/items/andlig-knives.f8a6a96e.webp", full: "/img/items/andlig-knives.914b6301.full.webp", w: 1200, h: 1200 },
  "anneland-mattress": { thumb: "/img/items/anneland-mattress.060cec40.webp", full: "/img/items/anneland-mattress.f2a76558.full.webp", w: 1200, h: 1200 },
  "annons-pot": { thumb: "/img/items/annons-pot.ce865b02.webp", full: "/img/items/annons-pot.3ae70cd9.full.webp", w: 1200, h: 1200 },
  "baerglim-sheet": { thumb: "/img/items/baerglim-sheet.670f0667.webp", full: "/img/items/baerglim-sheet.30be51c3.full.webp", w: 1200, h: 1200 },
  "bolmen-brush": { thumb: "/img/items/bolmen-brush.54d4ac87.webp", full: "/img/items/bolmen-brush.8e5fbf1f.full.webp", w: 1200, h: 1200 },
  "brunkrissla-bedding": { thumb: "/img/items/brunkrissla-bedding.368840ad.webp", full: "/img/items/brunkrissla-bedding.f4f44e50.full.webp", w: 1200, h: 1200 },
  "bumerang-hangers": { thumb: "/img/items/bumerang-hangers.e0648901.webp", full: "/img/items/bumerang-hangers.a564cf75.full.webp", w: 1200, h: 1200 },
  "ektandvinge-bedding": { thumb: "/img/items/ektandvinge-bedding.3ef6c6e1.webp", full: "/img/items/ektandvinge-bedding.eae67c33.full.webp", w: 1200, h: 1200 },
  "gaffelklocka-pillow": { thumb: "/img/items/gaffelklocka-pillow.28d443a8.webp", full: "/img/items/gaffelklocka-pillow.cd2cd417.full.webp", w: 1200, h: 1200 },
  "havstobis-containers": { thumb: "/img/items/havstobis-containers.b6bb613f.webp", full: "/img/items/havstobis-containers.017ad1b9.full.webp", w: 1200, h: 1200 },
  "hosvans-hangers": { thumb: "/img/items/hosvans-hangers.1ecd9131.webp", full: "/img/items/hosvans-hangers.899e6c33.full.webp", w: 1200, h: 1200 },
  "klunka-basket": { thumb: "/img/items/klunka-basket.64e96c29.webp", full: "/img/items/klunka-basket.88da0a98.full.webp", w: 1200, h: 1200 },
  "knorrhane-spatula": { thumb: "/img/items/knorrhane-spatula.0e069161.webp", full: "/img/items/knorrhane-spatula.ea9bd561.full.webp", w: 1200, h: 1200 },
  "mopsig-cutlery": { thumb: "/img/items/mopsig-cutlery.142080d5.webp", full: "/img/items/mopsig-cutlery.5b391f87.full.webp", w: 1200, h: 1200 },
  "oftast-bowl": { thumb: "/img/items/oftast-bowl.c34a6916.webp", full: "/img/items/oftast-bowl.2e615322.full.webp", w: 1200, h: 1200 },
  "oftast-plate-large": { thumb: "/img/items/oftast-plate-large.d047c520.webp", full: "/img/items/oftast-plate-large.2d6f45f5.full.webp", w: 1200, h: 1200 },
  "oftast-plate-small": { thumb: "/img/items/oftast-plate-small.cbe5d45e.webp", full: "/img/items/oftast-plate-small.54fe8e61.full.webp", w: 1200, h: 1200 },
  "pokal-glass": { thumb: "/img/items/pokal-glass.77f65c9c.webp", full: "/img/items/pokal-glass.9569b399.full.webp", w: 1200, h: 1200 },
  "rinnig-towels": { thumb: "/img/items/rinnig-towels.8159f203.webp", full: "/img/items/rinnig-towels.601a4944.full.webp", w: 1040, h: 1040 },
  "rort-spoon": { thumb: "/img/items/rort-spoon.f6b5b66b.webp", full: "/img/items/rort-spoon.143b4220.full.webp", w: 1200, h: 1200 },
  "rosenskarm-pillow": { thumb: "/img/items/rosenskarm-pillow.a51e71cd.webp", full: "/img/items/rosenskarm-pillow.4e052658.full.webp", w: 1200, h: 1200 },
  "safferot-duvet-warm": { thumb: "/img/items/safferot-duvet-warm.61c4d93f.webp", full: "/img/items/safferot-duvet-warm.cd8f6bb1.full.webp", w: 1200, h: 1200 },
  "sandgrasmal-duvet": { thumb: "/img/items/sandgrasmal-duvet.25bf0923.webp", full: "/img/items/sandgrasmal-duvet.fbd75cab.full.webp", w: 1200, h: 1200 },
  "sandgrasmal-pillow": { thumb: "/img/items/sandgrasmal-pillow.31fba49c.webp", full: "/img/items/sandgrasmal-pillow.e4359803.full.webp", w: 1200, h: 1200 },
  "solfibbla-bedding": { thumb: "/img/items/solfibbla-bedding.930a2ba0.webp", full: "/img/items/solfibbla-bedding.5f0a9002.full.webp", w: 1200, h: 1200 },
  "spruttig-hangers": { thumb: "/img/items/spruttig-hangers.e9f22179.webp", full: "/img/items/spruttig-hangers.8bbe81c3.full.webp", w: 1200, h: 1200 },
  "tagghaj-pan": { thumb: "/img/items/tagghaj-pan.8bb71cd0.webp", full: "/img/items/tagghaj-pan.211572e6.full.webp", w: 1200, h: 1200 },
  "tillreda-microwave": { thumb: "/img/items/tillreda-microwave.ac0f9651.webp", full: "/img/items/tillreda-microwave.8e797eb0.full.webp", w: 1200, h: 1200 },
  "tt-coffeemaker": { thumb: "/img/items/tt-coffeemaker.11cd4b97.webp", full: "/img/items/tt-coffeemaker.8ec5ead5.full.webp", w: 732, h: 732 },
  "tt-compost-bags": { thumb: "/img/items/tt-compost-bags.70aee95c.webp", full: "/img/items/tt-compost-bags.8c040164.full.webp", w: 500, h: 500 },
  "tt-conditioner": { thumb: "/img/items/tt-conditioner.a7827b74.webp", full: "/img/items/tt-conditioner.efdb5dd9.full.webp", w: 400, h: 999 },
  "tt-dish-brush": { thumb: "/img/items/tt-dish-brush.3a471f40.webp", full: "/img/items/tt-dish-brush.58e40d22.full.webp", w: 480, h: 339 },
  "tt-dish-detergent": { thumb: "/img/items/tt-dish-detergent.f644881c.webp", full: "/img/items/tt-dish-detergent.34ac59ca.full.webp", w: 225, h: 225 },
  "tt-garbage-bags": { thumb: "/img/items/tt-garbage-bags.18a65365.webp", full: "/img/items/tt-garbage-bags.0ec5a53d.full.webp", w: 732, h: 328 },
  "tt-handsoap": { thumb: "/img/items/tt-handsoap.b894adbe.webp", full: "/img/items/tt-handsoap.86e1a681.full.webp", w: 515, h: 197 },
  "tt-kettle": { thumb: "/img/items/tt-kettle.aad4ce53.webp", full: "/img/items/tt-kettle.e2643b87.full.webp", w: 555, h: 652 },
  "tt-laundry-detergent": { thumb: "/img/items/tt-laundry-detergent.a0f801ae.webp", full: "/img/items/tt-laundry-detergent.478ea0a9.full.webp", w: 202, h: 400 },
  "tt-mug": { thumb: "/img/items/tt-mug.15ac3f0c.webp", full: "/img/items/tt-mug.e2d01a41.full.webp", w: 710, h: 710 },
  "tt-shampoo": { thumb: "/img/items/tt-shampoo.0b5443d3.webp", full: "/img/items/tt-shampoo.c0261ac8.full.webp", w: 732, h: 732 },
  "tt-soapbar": { thumb: "/img/items/tt-soapbar.7990a86b.webp", full: "/img/items/tt-soapbar.4631a2dd.full.webp", w: 732, h: 732 },
  "tt-sponges": { thumb: "/img/items/tt-sponges.4ff9b1c9.webp", full: "/img/items/tt-sponges.b28ba817.full.webp", w: 732, h: 732 },
  "tt-toaster": { thumb: "/img/items/tt-toaster.b62cf4c0.webp", full: "/img/items/tt-toaster.87c0559d.full.webp", w: 732, h: 732 },
  "tt-toilet-cleaner": { thumb: "/img/items/tt-toilet-cleaner.76a860ca.webp", full: "/img/items/tt-toilet-cleaner.9ee9ffe1.full.webp", w: 346, h: 1024 },
  "tt-toiletpaper": { thumb: "/img/items/tt-toiletpaper.6fb959f0.webp", full: "/img/items/tt-toiletpaper.88295f4f.full.webp", w: 384, h: 336 },
  "tt-universal-spray": { thumb: "/img/items/tt-universal-spray.577672c4.webp", full: "/img/items/tt-universal-spray.bf72ccc3.full.webp", w: 732, h: 384 },
  "tt-window-spray": { thumb: "/img/items/tt-window-spray.8d861077.webp", full: "/img/items/tt-window-spray.cf18fb42.full.webp", w: 732, h: 488 },
  "vagsjon-bath-towel": { thumb: "/img/items/vagsjon-bath-towel.e8cb7a9f.webp", full: "/img/items/vagsjon-bath-towel.914a7f63.full.webp", w: 900, h: 900 },
  "vagsjon-hand-towel": { thumb: "/img/items/vagsjon-hand-towel.b5876a94.webp", full: "/img/items/vagsjon-hand-towel.ed002d0b.full.webp", w: 1040, h: 1040 },
  "vesteroy-mattress": { thumb: "/img/items/vesteroy-mattress.25dd2c80.webp", full: "/img/items/vesteroy-mattress.8b74588a.full.webp", w: 1200, h: 1200 },
};
